name: Build status(lot2)

on:
  push:
    branches: [ main ]
    paths:
      - lot2-ES/**

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd lot2-ES/ && make
