name: Build status(integration)

on:
  push:
    branches: [ main ]
    paths:
      - integration/**

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd integration/ && make
